### ISSUE TITLE
upload contacts

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-register#10]
The register server must provide a api function where you can upload a contact with all informations.

**Comment by enkore** [comment]
Please clarify: this specific API is intended so that one can search for many contacts at once?

Request: List-of-email/phone numbers

Response: List-of-List-of(public-key+drop-url+alias)

**Comment by enkore** [comment]
Feature removed from planning: would make scraping the directory contents too simple and throttling/rate-limiting too hard.
