### ISSUE TITLE
Verify the update and delete request

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-register#5]
If the [discussion](https://github.com/Qabel/qabel.github.io/pull/102#issuecomment-169647793) is completed, we should implement the result.

**Comment by thechauffeur** [comment]
We will use noise boxes.

**Comment by thechauffeur** [comment]
@jasinai the API of the register server should expect this is already done but until it is actually implemented just always behave as if the authentication is OK.

**Comment by audax** [comment]
verify with email sending instead
#6
